import Layout from "../components/layout/Layout";
import { motion } from "framer-motion";

const insights = [
  "Your spending pattern this month shows a healthy balance between growth and control.",
  "You’re allocating resources wisely—keep tracking weekly trends.",
  "Current expense behavior supports long-term creator sustainability.",
  "Smart spending decisions detected. Stay consistent.",
];

function Insights({ user, onLogout }) {
  const aiInsight = insights[Math.floor(Math.random() * insights.length)];

  return (
    <Layout user={user} onLogout={onLogout}>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <h1 style={{ marginBottom: "20px" }}>AI Insights</h1>

        <div className="card">
          <p style={{ fontSize: "18px" }}>{aiInsight}</p>
          <p style={{ fontSize: "14px", marginTop: "12px", color: "#c7a17a" }}>
            Generated by CoinTent AI
          </p>
        </div>
      </motion.div>
    </Layout>
  );
}

export default Insights;
